artifacts_root: artifacts


## Data Ingestion Config
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ArpitKadam/Chicken-Diseases-Classification-with-Fecal-Images/raw/refs/heads/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


## Model Preparation Config
prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


## Model Training Config
model_training:
  root_dir: artifacts/model_training
  trained_model_path: artifacts/model_training/trained_model.h5