artifacts_root: artifacts


## Data Ingestion Config
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ArpitKadam/Chicken-Diseases-Classification-with-Fecal-Images/raw/refs/heads/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  